/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vew;

import daoimp.Cliente_Impl;
import java.text.SimpleDateFormat;

import java.util.Date;
import javax.swing.JOptionPane;
import model.Cliente;
import model.Validacao;

/**
 *
 * @author jailson bom jesus
 */
public class Cliente_View extends javax.swing.JInternalFrame {

    /**
     * Creates new form Consultar_cliente
     */
    public Cliente_View() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        clitabela = new javax.swing.JTable();
        clipesquisa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        clitelefone = new javax.swing.JTextField();
        clinome = new javax.swing.JTextField();
        cligenero = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        clidistrito = new javax.swing.JComboBox<>();
        clizona = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        clinumeroducumento = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cliemail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        clidata = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        clipais = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        clitipo = new javax.swing.JComboBox<>();
        cliadd = new javax.swing.JToggleButton();
        cliedit = new javax.swing.JToggleButton();
        cliremove = new javax.swing.JToggleButton();
        jLabel13 = new javax.swing.JLabel();
        clitipodocumento = new javax.swing.JComboBox<>();
        cliid = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Clientes");
        setPreferredSize(new java.awt.Dimension(1100, 650));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/55369 (1).jpg"))); // NOI18N

        clitabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        clitabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clitabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(clitabela);

        clipesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                clipesquisaKeyReleased(evt);
            }
        });

        jLabel1.setText("Nome:");

        jLabel4.setText("Telefone:");

        jLabel3.setText("Nome:");

        cligenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino" }));
        cligenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cligeneroActionPerformed(evt);
            }
        });

        jLabel6.setText("Genero:");

        jLabel8.setText("Distrito:");

        clidistrito.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agua Grande", "Cantagalo", "Caué", "Lembá", "Lobata", "Mé Zoche", "Príncipe" }));

        jLabel10.setText("Data Nancimento:");

        jLabel5.setText("Zona:");

        jLabel7.setText("Nº de documento:");

        cliemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cliemailActionPerformed(evt);
            }
        });

        jLabel9.setText("Email:");

        jLabel11.setText("Nacionalidade:");

        clipais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Angolano(a)", "Brasilero(a)", "CaboVerdiano(a)", "Chinés(a)", "Guinense", "Moçanbicano(a)", "Sãotomense", "Português(a)", " " }));

        jLabel12.setText("Tipo:");

        clitipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fisico", "Juridico" }));

        cliadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addfun.png"))); // NOI18N
        cliadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cliaddActionPerformed(evt);
            }
        });

        cliedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editarfun.png"))); // NOI18N
        cliedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clieditActionPerformed(evt);
            }
        });

        cliremove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/deletefun.png"))); // NOI18N
        cliremove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cliremoveActionPerformed(evt);
            }
        });

        jLabel13.setText("Tipo de documento:");

        clitipodocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bilhete de Identidade", "Passaporte" }));

        cliid.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        cliid.setText("jLabel15");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1084, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(clinumeroducumento, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(230, 230, 230)
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(clitipo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(91, 91, 91))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(0, 304, Short.MAX_VALUE)
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(clipais, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(189, 189, 189)
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(clidistrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(81, 81, 81)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cligenero, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cliadd)
                                .addGap(154, 154, 154)
                                .addComponent(cliremove)
                                .addGap(130, 130, 130)
                                .addComponent(cliedit)))
                        .addGap(76, 76, 76))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clitipodocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cliemail, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(190, 190, 190))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cliid))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clipesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 284, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clidata, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(154, 154, 154)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clizona, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clinome, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(146, 146, 146)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clitelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(236, 236, 236))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(clipesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(clitelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(clinome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(clidistrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(clipais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel10)
                        .addComponent(clidata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(clizona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(clitipodocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cliemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9)))
                        .addGap(81, 81, 81))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(clinumeroducumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(clitipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cligenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cliadd, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(cliedit, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(cliremove))
                .addGap(69, 69, 69)
                .addComponent(cliid))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cliaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cliaddActionPerformed
        Cliente_Impl cd = new Cliente_Impl();
        Validacao val=new Validacao();
        Cliente c = new Cliente();
        c.setNome(clinome.getText());
        c.setData_de_nascimento(clidata.getDate());
        c.setPais(clipais.getSelectedItem().toString());
        c.setTipo_de_cliente(clitipo.getSelectedItem().toString());
        c.setTelefone(Long.parseLong(clitelefone.getText()));
        c.setZona(clizona.getText());
        c.setDistrito(clidistrito.getSelectedItem().toString());
        c.setGenero(cligenero.getSelectedItem().toString());
        c.setEmail(cliemail.getText());
        c.setTipo_de_documento(clitipodocumento.getSelectedItem().toString());
        c.setDocumento_de_identificacao(Integer.parseInt(clinumeroducumento.getText()));
        String s= val.validar_Data_Ano(clidata.getDate());
        if(s.length()==0){
        cd.adicionar(c);
        cd.pesquisar(clipesquisa.getText(), clitabela);
        clinome.setText("");
        clidata.setDate(null);
        clitelefone.setText("");
        clinome.setText("");
        clidata.setDate(null);
        clitelefone.setText("");
        cliemail.setText("");
        clinumeroducumento.setText("");
        clitelefone.setText("");
        }else{
            JOptionPane.showMessageDialog(null, s);
        }
    }//GEN-LAST:event_cliaddActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        Cliente_Impl cd = new Cliente_Impl();
        cd.pesquisar(clipesquisa.getText(), clitabela);
    }//GEN-LAST:event_formInternalFrameOpened

    private void clipesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clipesquisaKeyReleased
        Cliente_Impl cd = new Cliente_Impl();
        cd.pesquisar(clipesquisa.getText(), clitabela);
        cliadd.setVisible(true);
    }//GEN-LAST:event_clipesquisaKeyReleased

    private void clitabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clitabelaMouseClicked
        int i = clitabela.getSelectedRow();
        //cliid.setText(clitabela.getModel().getValueAt(i, 0).toString());
        clinome.setText(clitabela.getModel().getValueAt(i, 0).toString());
        clitelefone.setText(clitabela.getModel().getValueAt(i, 4).toString());
        cliemail.setText(clitabela.getModel().getValueAt(i, 8).toString());
        clidistrito.setSelectedItem(clitabela.getModel().getValueAt(i, 6).toString());
        cligenero.setSelectedItem(clitabela.getModel().getValueAt(i, 7).toString());
        clinumeroducumento.setText(clitabela.getModel().getValueAt(i, 10).toString());
        clipais.setSelectedItem(clitabela.getModel().getValueAt(i, 2).toString());
        clitipo.setSelectedItem(clitabela.getModel().getValueAt(i, 3).toString());
        clitipodocumento.setSelectedItem(clitabela.getModel().getValueAt(i, 9).toString());
        clizona.setText(clitabela.getModel().getValueAt(i, 5).toString());
        SimpleDateFormat sf=new SimpleDateFormat("dd/MMM/yyyy");
        clidata.setDateFormatString(clitabela.getModel().getValueAt(i, 1 ).toString());
        cliadd.setVisible(false);
        clidata.setEnabled(false);
        cligenero.setEnabled(false);
        clinome.setEnabled(false);
        clinumeroducumento.setEnabled(false);
        clipais.setEnabled(false);
        clitipo.setEnabled(false);
        clitipodocumento.setEnabled(false);
    }//GEN-LAST:event_clitabelaMouseClicked

    private void cligeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cligeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cligeneroActionPerformed

    private void cliemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cliemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cliemailActionPerformed

    private void cliremoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cliremoveActionPerformed
        Cliente_Impl cd = new Cliente_Impl();
        cd.remover(clitabela);
        cliadd.setVisible(true);
        clinome.setText("");
        clidata.setDate(null);
        clitelefone.setText("");
        cliemail.setText("");
        clinumeroducumento.setText("");
        clitelefone.setText("");
        cd.pesquisar(clipesquisa.getText(), clitabela);
        clidata.setEnabled(true);
        cligenero.setEnabled(true);
        clinome.setEnabled(true);
        clinumeroducumento.setEnabled(true);
        clipais.setEnabled(true);
        clitipo.setEnabled(true);
        clitipodocumento.setEnabled(true);
    }//GEN-LAST:event_cliremoveActionPerformed

    private void clieditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clieditActionPerformed
        Cliente c = new Cliente();
        Cliente_Impl cd = new Cliente_Impl();
        c.setNome(clinome.getText());
        c.setData_de_nascimento(clidata.getDate());
        c.setPais(clipais.getSelectedItem().toString());
        c.setTipo_de_cliente(clitipo.getSelectedItem().toString());
        c.setTelefone(Long.parseLong(clitelefone.getText()));
        c.setZona(clizona.getText());
        c.setDistrito(clidistrito.getSelectedItem().toString());
        c.setGenero(cligenero.getSelectedItem().toString());
        c.setEmail(cliemail.getText());
        c.setTipo_de_documento(clitipodocumento.getSelectedItem().toString());
        c.setDocumento_de_identificacao(Integer.parseInt(clinumeroducumento.getText()));
        cd.editar(c);
        cd.pesquisar(clipesquisa.getText(), clitabela);
        clinome.setText("");
        clidata.setDate(null);
        clitelefone.setText("");
        cliemail.setText("");
        clinumeroducumento.setText("");
        clitelefone.setText("");
        clidata.setEnabled(true);
        cligenero.setEnabled(true);
        clinome.setEnabled(true);
        clinumeroducumento.setEnabled(true);
        clipais.setEnabled(true);
        clitipo.setEnabled(true);
        clitipodocumento.setEnabled(true);
        clizona.setText("");
    }//GEN-LAST:event_clieditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton cliadd;
    private com.toedter.calendar.JDateChooser clidata;
    private javax.swing.JComboBox<String> clidistrito;
    private javax.swing.JToggleButton cliedit;
    private javax.swing.JTextField cliemail;
    private javax.swing.JComboBox<String> cligenero;
    private javax.swing.JLabel cliid;
    private javax.swing.JTextField clinome;
    private javax.swing.JTextField clinumeroducumento;
    private javax.swing.JComboBox<String> clipais;
    private javax.swing.JTextField clipesquisa;
    private javax.swing.JToggleButton cliremove;
    private javax.swing.JTable clitabela;
    private javax.swing.JTextField clitelefone;
    private javax.swing.JComboBox<String> clitipo;
    private javax.swing.JComboBox<String> clitipodocumento;
    private javax.swing.JTextField clizona;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
