/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vew;

import daoimp.Empresa_Impl;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Conexao;
import model.Empresa;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author jailson bom jesus
 */
public class Empresa_Vew extends javax.swing.JInternalFrame {

    PreparedStatement ps = null;
    Connection co = null;
    ResultSet rs = null;

    /**
     * Creates new form Consultar_empresa
     */
    public Empresa_Vew() {
        initComponents();
        co = Conexao.conectar();
    }
 
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        empaitabela = new javax.swing.JScrollPane();
        emptabela = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        emppesquisa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        empid = new javax.swing.JLabel();
        empainel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        empnome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        empdistrito = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        empzona = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        empnfuncionarios = new javax.swing.JTextField();
        empsave = new javax.swing.JToggleButton();
        empremove = new javax.swing.JToggleButton();
        empedit = new javax.swing.JToggleButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Empresa");
        setPreferredSize(new java.awt.Dimension(1100, 650));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        empaitabela.setPreferredSize(new java.awt.Dimension(1350, 100));

        emptabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Distrito", "Zona", "Qunatidade de Funcionarios"
            }
        ));
        emptabela.setSelectionBackground(new java.awt.Color(255, 0, 0));
        emptabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emptabelaMouseClicked(evt);
            }
        });
        empaitabela.setViewportView(emptabela);

        jLabel1.setText("Nome:");

        emppesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emppesquisaKeyReleased(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/55369 (1).jpg"))); // NOI18N

        empid.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        empid.setText("jLabel8");

        jLabel3.setText("Nome:");

        jLabel4.setText("Distrito:");

        empdistrito.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "..............", "Agua Grande", "Cantagalo", "Caué", "Lembá", "Lobata", "Mé Zoche", "Príncipe" }));
        empdistrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empdistritoActionPerformed(evt);
            }
        });

        jLabel5.setText("Zona:");

        jLabel6.setText("Nº de funcionarios:");

        empsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/download.2.003 (1).jpg"))); // NOI18N
        empsave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        empsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empsaveActionPerformed(evt);
            }
        });

        empremove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images (1).jpg"))); // NOI18N
        empremove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        empremove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empremoveActionPerformed(evt);
            }
        });

        empedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.jpg"))); // NOI18N
        empedit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        empedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empeditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout empainelLayout = new javax.swing.GroupLayout(empainel);
        empainel.setLayout(empainelLayout);
        empainelLayout.setHorizontalGroup(
            empainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, empainelLayout.createSequentialGroup()
                .addGroup(empainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(empainelLayout.createSequentialGroup()
                        .addGap(413, 413, 413)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(empnome, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4))
                    .addGroup(empainelLayout.createSequentialGroup()
                        .addGap(376, 376, 376)
                        .addComponent(empsave)
                        .addGap(142, 142, 142)
                        .addComponent(empedit, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, empainelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(empnfuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(empainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(empainelLayout.createSequentialGroup()
                        .addComponent(empdistrito, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(214, 214, 214))
                    .addGroup(empainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(empainelLayout.createSequentialGroup()
                            .addComponent(empzona, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(145, 145, 145))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, empainelLayout.createSequentialGroup()
                            .addComponent(empremove)
                            .addGap(219, 219, 219)))))
        );
        empainelLayout.setVerticalGroup(
            empainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, empainelLayout.createSequentialGroup()
                .addGroup(empainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(empdistrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addGroup(empainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empzona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(empnfuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addGroup(empainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(empsave)
                    .addComponent(empedit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empremove, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(empaitabela, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emppesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(empid))
            .addComponent(empainel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(emppesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addComponent(jLabel7)
                    .addComponent(empid))
                .addGap(18, 18, 18)
                .addComponent(empaitabela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(empainel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void empdistritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empdistritoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empdistritoActionPerformed

    private void empsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empsaveActionPerformed
        if (!empnfuncionarios.getText().equals("") && !empnome.getText().equals("") && !empzona.getText().equals("")) {
            Empresa_Impl ed = new Empresa_Impl();
            Empresa e = new Empresa();
            e.setNome(empnome.getText());
            e.setZona(empzona.getText());
            e.setDistrito(empdistrito.getSelectedItem().toString());
            e.setNfuncionarios(Integer.parseInt(empnfuncionarios.getText()));
            ed.inserir(e);
            empnome.setText("");
            empzona.setText("");
            empnfuncionarios.setText("");
            ed.pesquisar(emppesquisa.getText(), emptabela);
        } else {
            JOptionPane.showMessageDialog(null, "Por favor preenche os espaços em branco");
        }
    }//GEN-LAST:event_empsaveActionPerformed

    private void emppesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emppesquisaKeyReleased
        // TODO add your handling code here:
        Empresa_Impl ed = new Empresa_Impl();
        ed.pesquisar(emppesquisa.getText(), emptabela);
    }//GEN-LAST:event_emppesquisaKeyReleased

    private void empremoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empremoveActionPerformed
        int i = JOptionPane.showConfirmDialog(null, "Tens sertesa que queres deletar", "Deletar", JOptionPane.OK_CANCEL_OPTION);
        if (i == JOptionPane.OK_OPTION) {
            Empresa_Impl ed = new Empresa_Impl();
            ed.remover(emptabela);
            ed.pesquisar(emppesquisa.getText(), emptabela);
            empnome.setText("");
            empzona.setText("");
            empnfuncionarios.setText("");
            empsave.setVisible(true);
        }
    }//GEN-LAST:event_empremoveActionPerformed

    private void empeditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empeditActionPerformed
        Empresa em = new Empresa();
        Empresa_Impl ed = new Empresa_Impl();
        em.setNome(empnome.getText());
        em.setZona(empzona.getText());
        em.setDistrito(empdistrito.getSelectedItem().toString());
        em.setNfuncionarios(Integer.parseInt(empnfuncionarios.getText()));
        ed.editar(em,emptabela);
        ed.pesquisar(emppesquisa.getText(), emptabela);
        empnome.setText("");
        empzona.setText("");
        empnfuncionarios.setText("");
        empsave.setVisible(true);

    }//GEN-LAST:event_empeditActionPerformed

    private void emptabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emptabelaMouseClicked
        int i = emptabela.getSelectedRow();
        //empid.setText(emptabela.getModel().getValueAt(i, 0).toString());
        empnome.setText(emptabela.getModel().getValueAt(i, 0).toString());
        empzona.setText(emptabela.getModel().getValueAt(i, 2).toString());
        empnfuncionarios.setText(emptabela.getModel().getValueAt(i, 3).toString());
        empsave.setVisible(false);
        Dimension d = new Dimension();
        d.height = 500;
        d.width = 500;
        emptabela.setMaximumSize(d);
    }//GEN-LAST:event_emptabelaMouseClicked

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened

      Empresa_Impl ed = new Empresa_Impl();
      ed.pesquisar(emppesquisa.getText(), emptabela);
        
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel empainel;
    public static javax.swing.JScrollPane empaitabela;
    private javax.swing.JComboBox<String> empdistrito;
    private javax.swing.JToggleButton empedit;
    private javax.swing.JLabel empid;
    private javax.swing.JTextField empnfuncionarios;
    private javax.swing.JTextField empnome;
    private javax.swing.JTextField emppesquisa;
    private javax.swing.JToggleButton empremove;
    private javax.swing.JToggleButton empsave;
    public static javax.swing.JTable emptabela;
    private javax.swing.JTextField empzona;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
