/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vew;

import daoimp.Funcionario_Impl;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Funcionario;

/**
 *
 * @author jailson bom jesus
 */
public class Funcionario_View extends javax.swing.JInternalFrame {

    /**
     * Creates new form Consultar_funcionario
     */
    public Funcionario_View() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        funpaitabela = new javax.swing.JScrollPane();
        funtabela = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        funpesquisa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        funpane = new javax.swing.JPanel();
        funrestrito = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        funsenha = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        funusuario = new javax.swing.JTextField();
        fundata = new com.toedter.calendar.JDateChooser();
        funstatus = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        funiditar = new javax.swing.JToggleButton();
        funremover = new javax.swing.JToggleButton();
        funsalvar = new javax.swing.JToggleButton();
        fungenero = new javax.swing.JComboBox<>();
        funzona = new javax.swing.JTextField();
        fundistrito = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        funsalario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        funome = new javax.swing.JTextField();
        funtelemovel = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        idfun = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Funcionario");
        setPreferredSize(new java.awt.Dimension(1100, 650));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        funpaitabela.setPreferredSize(new java.awt.Dimension(1100, 100));

        funtabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        funtabela.setPreferredSize(new java.awt.Dimension(600, 494));
        funtabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                funtabelaMouseClicked(evt);
            }
        });
        funpaitabela.setViewportView(funtabela);

        jLabel1.setText("Nome:");

        funpesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                funpesquisaKeyReleased(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/55369 (1).jpg"))); // NOI18N

        funrestrito.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Login", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 255, 0))); // NOI18N

        jLabel11.setText("Senha:");

        jLabel12.setText("Nome de Usuario:");

        javax.swing.GroupLayout funrestritoLayout = new javax.swing.GroupLayout(funrestrito);
        funrestrito.setLayout(funrestritoLayout);
        funrestritoLayout.setHorizontalGroup(
            funrestritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, funrestritoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(funrestritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(funrestritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(funusuario, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(funsenha))
                .addGap(49, 49, 49))
        );
        funrestritoLayout.setVerticalGroup(
            funrestritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(funrestritoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(funrestritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(funusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(funrestritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(funsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        funstatus.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        funstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gerente", "Funcionario" }));
        funstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funstatusActionPerformed(evt);
            }
        });

        jLabel9.setText("Status:");

        funiditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.profile.vector.icon.jpg"))); // NOI18N
        funiditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funiditarActionPerformed(evt);
            }
        });

        funremover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/remove.user.vector.icon.jpg"))); // NOI18N
        funremover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funremoverActionPerformed(evt);
            }
        });

        funsalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images.jpg"))); // NOI18N
        funsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funsalvarActionPerformed(evt);
            }
        });

        fungenero.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        fungenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino" }));
        fungenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fungeneroActionPerformed(evt);
            }
        });

        funzona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funzonaActionPerformed(evt);
            }
        });

        fundistrito.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        fundistrito.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agua Grande", "Cantagalo", "Caué", "Lembá", "Lobata", "Mé Zoche", "Príncipe" }));
        fundistrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fundistritoActionPerformed(evt);
            }
        });

        jLabel8.setText("Distrito:");

        jLabel7.setText("Salário:");

        jLabel6.setText("Genero:");

        jLabel5.setText("Telefone/Telemovel:");

        jLabel4.setText("Zona:");

        jLabel3.setText("Nome:");

        jLabel10.setText("Data Nancimento:");

        idfun.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        idfun.setText("jLabel11");

        javax.swing.GroupLayout funpaneLayout = new javax.swing.GroupLayout(funpane);
        funpane.setLayout(funpaneLayout);
        funpaneLayout.setHorizontalGroup(
            funpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(funpaneLayout.createSequentialGroup()
                .addContainerGap(258, Short.MAX_VALUE)
                .addGroup(funpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(funpaneLayout.createSequentialGroup()
                        .addGroup(funpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel10)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(funpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(funpaneLayout.createSequentialGroup()
                                .addComponent(funzona, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8))
                            .addGroup(funpaneLayout.createSequentialGroup()
                                .addComponent(fundata, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9))
                            .addGroup(funpaneLayout.createSequentialGroup()
                                .addGroup(funpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(funome, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(funsalario, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(81, 81, 81)
                                .addGroup(funpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(funpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fundistrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fungenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(funstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(funtelemovel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(funpaneLayout.createSequentialGroup()
                        .addComponent(funrestrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addGroup(funpaneLayout.createSequentialGroup()
                        .addComponent(funremover)
                        .addGap(108, 108, 108)
                        .addComponent(funiditar)))
                .addGap(279, 279, 279))
            .addGroup(funpaneLayout.createSequentialGroup()
                .addComponent(idfun)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(funsalvar)
                .addGap(628, 628, 628))
        );
        funpaneLayout.setVerticalGroup(
            funpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, funpaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(idfun)
                .addContainerGap())
            .addGroup(funpaneLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(funpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(funome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(fungenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(funpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(funsalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(funtelemovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(funpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(fundata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(funpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(funstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(funpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(funzona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(fundistrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(funrestrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(funpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(funiditar)
                    .addComponent(funremover)
                    .addComponent(funsalvar)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(funpaitabela, javax.swing.GroupLayout.DEFAULT_SIZE, 1084, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(funpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(funpane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(funpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(funpaitabela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(funpane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void funsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funsalvarActionPerformed
        Funcionario_Impl fd = new Funcionario_Impl();
        Funcionario f = new Funcionario();
        f.setNome(funome.getText());
        f.setData_de_nascimento(fundata.getDate());
        f.setDistrito(fundistrito.getSelectedItem().toString());
        f.setGenero(fungenero.getSelectedItem().toString());
        f.setZona(funzona.getText());
        f.setSalario(Double.parseDouble(funsalario.getText()));
        f.setTelefone(Long.parseLong(funtelemovel.getText()));
        f.setStatus(funstatus.getSelectedItem().toString());
        f.setSenha(new String(funsenha.getPassword()));
        f.setNome_de_usuario(funusuario.getText());
        fd.adicionar(f);
        fd.pesquisar(funpesquisa.getText(), funtabela);
        funome.setText("");
        funsenha.setText("");
        funusuario.setText("");
        fundata.setDate(null);
        funzona.setText("");
        funsalario.setText("");
        funtelemovel.setText("");
    }//GEN-LAST:event_funsalvarActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        Funcionario_Impl fd = new Funcionario_Impl();
        fd.pesquisar(funpesquisa.getText(), funtabela);
    }//GEN-LAST:event_formInternalFrameOpened

    private void funremoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funremoverActionPerformed
        int i = JOptionPane.showConfirmDialog(null, "Tens sertesa que queres deletar", "Deletar", JOptionPane.OK_CANCEL_OPTION);
        if (i == JOptionPane.OK_OPTION) {
            Funcionario_Impl fd = new Funcionario_Impl();
            fd.remover(funtabela);
            fd.pesquisar(funpesquisa.getText(), funtabela);
            funrestrito.setVisible(true);
            funome.setText("");
            funsenha.setText("");
            funusuario.setText("");
            fundata.setDate(null);
            funzona.setText("");
            funsalario.setText("");
            funtelemovel.setText("");
            funsalvar.setVisible(true);
        }
    }//GEN-LAST:event_funremoverActionPerformed

    private void funpesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_funpesquisaKeyReleased
        Funcionario_Impl fd = new Funcionario_Impl();
        fd.pesquisar(funpesquisa.getText(), funtabela);
    }//GEN-LAST:event_funpesquisaKeyReleased

    private void funiditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funiditarActionPerformed
        Funcionario f = new Funcionario();
        Funcionario_Impl fd = new Funcionario_Impl();
        //f.setId(Integer.parseInt(idfun.getText()));
        //f.setNome(funome.getText());
        //f.setData_de_nascimento(fundata.getDate());
        f.setDistrito(fundistrito.getSelectedItem().toString());
        f.setGenero(fungenero.getSelectedItem().toString());
        f.setZona(funzona.getText());
        f.setSalario(Double.parseDouble(funsalario.getText()));
        f.setTelefone(Long.parseLong(funtelemovel.getText()));
        f.setStatus(funstatus.getSelectedItem().toString());
        f.setSenha(new String(funsenha.getPassword()));
        f.setNome_de_usuario(funusuario.getText());
        f.setNome(funome.getText());
        f.setTelefone(Integer.parseInt(funtelemovel.getText()));
        fd.editar(f,funtabela);
        funrestrito.setVisible(true);
        funome.setText("");
        funsenha.setText("");
        funusuario.setText("");
        fundata.setDate(null);
        funzona.setText("");
        funsalario.setText("");
        funtelemovel.setText("");
        fd.pesquisar(funpesquisa.getText(), funtabela);
        funsalvar.setVisible(true);
    }//GEN-LAST:event_funiditarActionPerformed

    private void funtabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_funtabelaMouseClicked
        int i = funtabela.getSelectedRow();
        //idfun.setText(funtabela.getModel().getValueAt(i, 0).toString());
        funome.setText(funtabela.getModel().getValueAt(i, 0).toString());
        funome.setEnabled(false);
        funzona.setText(funtabela.getModel().getValueAt(i, 2).toString());
        funsalario.setText(funtabela.getModel().getValueAt(i, 5).toString());
        fundata.setEnabled(false);
        funtelemovel.setText(funtabela.getModel().getValueAt(i, 6).toString());
        //funsenha.setText(funtabela.getModel().getValueAt(i, 8).toString());
        //funusuario.setText(funtabela.getModel().getValueAt(i, 9).toString());
        funrestrito.setVisible(false);
        funsalvar.setVisible(false);
        fungenero.setEnabled(false);
    }//GEN-LAST:event_funtabelaMouseClicked

    private void funstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funstatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_funstatusActionPerformed

    private void fundistritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fundistritoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fundistritoActionPerformed

    private void funzonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funzonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_funzonaActionPerformed

    private void fungeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fungeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fungeneroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser fundata;
    private javax.swing.JComboBox<String> fundistrito;
    private javax.swing.JComboBox<String> fungenero;
    private javax.swing.JToggleButton funiditar;
    private javax.swing.JTextField funome;
    public static javax.swing.JScrollPane funpaitabela;
    public static javax.swing.JPanel funpane;
    private javax.swing.JTextField funpesquisa;
    private javax.swing.JToggleButton funremover;
    private javax.swing.JPanel funrestrito;
    private javax.swing.JTextField funsalario;
    private javax.swing.JToggleButton funsalvar;
    private javax.swing.JPasswordField funsenha;
    private javax.swing.JComboBox<String> funstatus;
    public static javax.swing.JTable funtabela;
    private javax.swing.JTextField funtelemovel;
    private javax.swing.JTextField funusuario;
    private javax.swing.JTextField funzona;
    private javax.swing.JLabel idfun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
