/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vew;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static java.lang.System.exit;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import static java.time.Instant.now;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
//import java.awt.Graphics;
import javax.swing.*;
import model.Conexao;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author jailson bom jesus
 */
public class Menu_View extends javax.swing.JFrame {

    Connection co;

    /**
     * Creates new form Menu
     */
    public Menu_View() {
        co = Conexao.conectar();
        initComponents();
        horadata();
    }

    public void horadata() {
        Date date = new Date();
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        mendata.setText(df.format(date));
        Timer tim = new Timer(1000, new hora());
        tim.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        menpanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        conf = new javax.swing.JButton();
        nomeusuario = new javax.swing.JLabel();
        mendata = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ImageIcon ic=new ImageIcon(getClass().getResource("/images/pri.jpg"));
        Image im = ic.getImage();
        mendesktop = new javax.swing.JDesktopPane(){

            public void paintComponent(Graphics g){
                g.drawImage(im,0,0,getWidth(),getHeight(),this);
            }
        };
        menhora = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        statusfun = new javax.swing.JLabel();
        funeditrestrito = new javax.swing.JButton();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");

        menpanel.setPreferredSize(new java.awt.Dimension(1350, 700));
        menpanel.setLayout(null);

        jToggleButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/company_22169.png"))); // NOI18N
        jToggleButton6.setText("Empresa");
        jToggleButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6ActionPerformed(evt);
            }
        });

        jToggleButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1486146612-propertyagent002_79450.png"))); // NOI18N
        jToggleButton5.setText("Funcionario");
        jToggleButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });

        jToggleButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ExecutiveCar_Black_icon-icons.com_54904.png"))); // NOI18N
        jToggleButton4.setText("Carro");
        jToggleButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });

        jToggleButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/customer_person_people_man_user_client_1629 (1).png"))); // NOI18N
        jToggleButton3.setText("Cliente");
        jToggleButton3.setToolTipText("");
        jToggleButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rentacar_89116.png"))); // NOI18N
        jToggleButton2.setText("Aluguel");
        jToggleButton2.setToolTipText("Alugar carro");
        jToggleButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pngtree.report.line.filled.icon.png.image_324854.jpg"))); // NOI18N
        jToggleButton1.setText("Relatórios");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/download.2.000.jpg"))); // NOI18N
        jToggleButton7.setText("Venda");
        jToggleButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton7ActionPerformed(evt);
            }
        });

        jToggleButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/devolution (1).jpg"))); // NOI18N
        jToggleButton8.setText("Devolução");
        jToggleButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton8ActionPerformed(evt);
            }
        });

        conf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/confi (1).png"))); // NOI18N
        conf.setText("Configuraçõe");
        conf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToggleButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToggleButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToggleButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(conf)
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conf))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        menpanel.add(jPanel3);
        jPanel3.setBounds(0, 0, 1240, 40);

        nomeusuario.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        nomeusuario.setText("Nome");
        menpanel.add(nomeusuario);
        nomeusuario.setBounds(1190, 50, 140, 30);

        mendata.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mendata.setText("data");
        menpanel.add(mendata);
        mendata.setBounds(1150, 620, 170, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/850_400_carros.chineses.a.venda.em.portugal.jpg"))); // NOI18N
        menpanel.add(jLabel3);
        jLabel3.setBounds(1130, 250, 190, 100);

        mendesktop.setPreferredSize(new java.awt.Dimension(1100, 650));

        javax.swing.GroupLayout mendesktopLayout = new javax.swing.GroupLayout(mendesktop);
        mendesktop.setLayout(mendesktopLayout);
        mendesktopLayout.setHorizontalGroup(
            mendesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );
        mendesktopLayout.setVerticalGroup(
            mendesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        menpanel.add(mendesktop);
        mendesktop.setBounds(0, 40, 1100, 650);

        menhora.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        menhora.setText("hora");
        menpanel.add(menhora);
        menhora.setBounds(1150, 500, 150, 60);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logout_37127.png"))); // NOI18N
        jButton1.setToolTipText("Sair");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        menpanel.add(jButton1);
        jButton1.setBounds(1270, 0, 73, 40);

        statusfun.setText("jLabel1");
        menpanel.add(statusfun);
        statusfun.setBounds(1300, 660, 34, 14);

        funeditrestrito.setText("Editar login");
        funeditrestrito.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        funeditrestrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funeditrestritoActionPerformed(evt);
            }
        });
        menpanel.add(funeditrestrito);
        funeditrestrito.setBounds(0, 0, 57, 19);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
        // TODO add your handling code here:
        Empresa_Vew ev = new Empresa_Vew();
        ev.setVisible(true);
        mendesktop.add(ev);
        if (statusfun.getText().equals("Funcionario")) {
            ev.empainel.setVisible(false);
            Dimension d = new Dimension();
            d.height = 1350;
            d.width = 300;
            //ev.emptabela.setPreferredSize(d);
            ev.empaitabela.setPreferredSize(d);
        }
    }//GEN-LAST:event_jToggleButton6ActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        Funcionario_View fv = new Funcionario_View();
        fv.setVisible(true);
        mendesktop.add(fv);
        if (statusfun.getText().equals("Funcionario")) {
            fv.funpane.setVisible(false);
            Dimension d = new Dimension();
            d.height = 1350;
            d.width = 300;
            //ev.emptabela.setPreferredSize(d);
            fv.funpaitabela.setPreferredSize(d);
        }
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        Carro_View c = new Carro_View();
        c.setVisible(true);
        mendesktop.add(c);
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        Cliente_View cv = new Cliente_View();
        cv.setVisible(true);
        mendesktop.add(cv);
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        Alugar_View av = new Alugar_View();
        av.setVisible(true);
        mendesktop.add(av);
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
         Escolha_Relatorio_View er=new Escolha_Relatorio_View();
         er.setVisible(true);
         mendesktop.add(er);
         
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton7ActionPerformed
        Venda_View vv = new Venda_View();
        vv.setVisible(true);
        mendesktop.add(vv);
    }//GEN-LAST:event_jToggleButton7ActionPerformed

    private void jToggleButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton8ActionPerformed
        Devolucao_View dv = new Devolucao_View();
        dv.setVisible(true);
        mendesktop.add(dv);
    }//GEN-LAST:event_jToggleButton8ActionPerformed

    private void funeditrestritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funeditrestritoActionPerformed

    }//GEN-LAST:event_funeditrestritoActionPerformed

    private void confActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confActionPerformed
        Confirmar_Login_View cl=new Confirmar_Login_View();
        cl.setVisible(true);
        mendesktop.add(cl);
    }//GEN-LAST:event_confActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton conf;
    private javax.swing.JButton funeditrestrito;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private static javax.swing.JLabel mendata;
    javax.swing.JDesktopPane mendesktop;
    private javax.swing.JLabel menhora;
    private javax.swing.JPanel menpanel;
    public static javax.swing.JLabel nomeusuario;
    public static javax.swing.JLabel statusfun;
    // End of variables declaration//GEN-END:variables
class hora implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            Calendar ca = Calendar.getInstance();
            menhora.setText(String.format("%1$tH:%1$tM:%1$tS", ca));
        }

    }

}
