/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vew;

import daoimp.Carro_Impl;
import daoimp.Cliente_Impl;
import daoimp.Venda_Impl;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import model.Aluguel;
import model.Venda;

/**
 *
 * @author jailson bom jesus
 */
public class Venda_View extends javax.swing.JInternalFrame {

    /**
     * Creates new form Vendaview
     */
    public Venda_View() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aluprincipal = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        venclitabela = new javax.swing.JTable();
        venclipesquisa = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        venaddcliente = new javax.swing.JButton();
        vennomcliente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        veninicio = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        venplacarro = new javax.swing.JFormattedTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        vencartabela = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        vencarpesquisa = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        venhorainicio = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Venda");
        setPreferredSize(new java.awt.Dimension(1100, 650));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        aluprincipal.setPreferredSize(new java.awt.Dimension(1100, 650));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(0, 0, 255))); // NOI18N

        venclitabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        venclitabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                venclitabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(venclitabela);

        venclipesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                venclipesquisaActionPerformed(evt);
            }
        });
        venclipesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                venclipesquisaKeyReleased(evt);
            }
        });

        jLabel7.setText("Nome:");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/55369 (1).jpg"))); // NOI18N

        venaddcliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addfun.png"))); // NOI18N
        venaddcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                venaddclienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(venclipesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(venaddcliente)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(venclipesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(venaddcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jLabel1.setText("Cliente:");

        jLabel3.setText("Data de venda:");

        jLabel6.setText("Placa:");

        try {
            venplacarro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("STP-##-##A")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3393111_stock.vector.sale.car.icon.jpg"))); // NOI18N
        jToggleButton1.setToolTipText("Alugar");
        jToggleButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Carro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(0, 0, 255))); // NOI18N

        vencartabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        vencartabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vencartabelaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(vencartabela);

        jLabel5.setText("Marca:");

        vencarpesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                vencarpesquisaKeyReleased(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/55369 (1).jpg"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/55369 (1).jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vencarpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(207, 207, 207)
                    .addComponent(jLabel8)
                    .addContainerGap(270, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(vencarpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(145, 145, 145)
                    .addComponent(jLabel8)
                    .addContainerGap(146, Short.MAX_VALUE)))
        );

        venhorainicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "07:00", "07:30", "08:00", "08:30", "09:00", "09:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", "18:30", "19:00", "19:30", "20:00" }));
        venhorainicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                venhorainicioActionPerformed(evt);
            }
        });

        jLabel10.setText("Hora da venda:");

        javax.swing.GroupLayout aluprincipalLayout = new javax.swing.GroupLayout(aluprincipal);
        aluprincipal.setLayout(aluprincipalLayout);
        aluprincipalLayout.setHorizontalGroup(
            aluprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aluprincipalLayout.createSequentialGroup()
                .addGap(302, 302, 302)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vennomcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(venplacarro, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(aluprincipalLayout.createSequentialGroup()
                .addGroup(aluprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(aluprincipalLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(aluprincipalLayout.createSequentialGroup()
                        .addGroup(aluprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(aluprincipalLayout.createSequentialGroup()
                                .addGap(509, 509, 509)
                                .addComponent(jToggleButton1))
                            .addGroup(aluprincipalLayout.createSequentialGroup()
                                .addGap(265, 265, 265)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(veninicio, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(117, 117, 117)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(venhorainicio, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        aluprincipalLayout.setVerticalGroup(
            aluprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aluprincipalLayout.createSequentialGroup()
                .addGroup(aluprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(aluprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(vennomcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(venplacarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(aluprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(veninicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addGroup(aluprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(venhorainicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(75, 75, 75)
                .addComponent(jToggleButton1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(aluprincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 1084, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(aluprincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void venclitabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_venclitabelaMouseClicked
        int i = venclitabela.getSelectedRow();
        vennomcliente.setText(venclitabela.getModel().getValueAt(i, 0).toString());
    }//GEN-LAST:event_venclitabelaMouseClicked

    private void venclipesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_venclipesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_venclipesquisaActionPerformed

    private void venclipesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_venclipesquisaKeyReleased
        Cliente_Impl cd = new Cliente_Impl();
        cd.pesquisarav(venclipesquisa.getText(), venclitabela);
    }//GEN-LAST:event_venclipesquisaKeyReleased

    private void venaddclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_venaddclienteActionPerformed
        Cliente_View cv = new Cliente_View();
        Menu_View me = new Menu_View();
        aluprincipal.setVisible(false);
        cv.setVisible(true);
        this.add(cv);
        //  me.mendesktop.add(cv);
    }//GEN-LAST:event_venaddclienteActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        Date date = new Date();
        boolean b = true;
        SimpleDateFormat sf = new SimpleDateFormat("dd/MM/yyyy");
        if (veninicio.getDate().getYear() < date.getYear()) {
            b = false;
            JOptionPane.showMessageDialog(null, "O ano que preencheste não é aceitavel!", "Erro no ano", JOptionPane.ERROR_MESSAGE);
        } else {
            if (veninicio.getDate().getMonth() < date.getMonth()) {
                b = false;
                JOptionPane.showMessageDialog(null, "O mês que preencheste não é aceitavel!", "Erro no mês", JOptionPane.ERROR_MESSAGE);
            } else {
                if (Integer.parseInt(sf.format(veninicio.getDate()).subSequence(0, 2).toString()) < Integer.parseInt(sf.format(date).subSequence(0, 2).toString())) {
                    if (veninicio.getDate().getMonth() == date.getMonth()) {
                        b = false;
                        JOptionPane.showMessageDialog(null, "O dia que preencheste não é aceitavel!", "Erro no dia", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    if (Integer.parseInt(venhorainicio.getSelectedItem().toString().subSequence(0, 2).toString()) < date.getHours()) {
                        if (veninicio.getDate().getYear() < date.getYear()) {
                            if (veninicio.getDate().getMonth() < date.getMonth()) {
                                if (Integer.parseInt(sf.format(veninicio.getDate()).subSequence(0, 2).toString()) == Integer.parseInt(sf.format(date).subSequence(0, 2).toString())) {
                                    b = false;
                                    JOptionPane.showMessageDialog(null, "A hora que preencheste não é aceitavel", "Erro na hora", JOptionPane.ERROR_MESSAGE);
                                }
                            }
                        }
                    }
                }
            }
        }
        if (b == true) {
            Venda v = new Venda();
            Venda_Impl vd = new Venda_Impl();
            Carro_Impl cd = new Carro_Impl();
            v.setData_inicial(veninicio.getDate());
            v.setHora_inicial(venhorainicio.getSelectedItem().toString());
            v.setNome_do_cliente(vennomcliente.getText());
            v.setPlaca_de_carro(venplacarro.getText());
            vd.vender(v);
            cd.removerav(venplacarro.getText());
            cd.pesquisarava(vencarpesquisa.getText(),vencartabela);
            veninicio.setDate(null);
            vennomcliente.setText("");
            venplacarro.setText("");
            
        }

    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void vencartabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vencartabelaMouseClicked
        int i = vencartabela.getSelectedRow();
        venplacarro.setText(vencartabela.getModel().getValueAt(i, 3).toString());
    }//GEN-LAST:event_vencartabelaMouseClicked

    private void vencarpesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vencarpesquisaKeyReleased
        Carro_Impl cad = new Carro_Impl();
        cad.pesquisarava(vencarpesquisa.getText(),vencartabela);
    }//GEN-LAST:event_vencarpesquisaKeyReleased

    private void venhorainicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_venhorainicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_venhorainicioActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        Cliente_Impl cd = new Cliente_Impl();
        cd.pesquisarav(venclipesquisa.getText(), venclitabela);
        Carro_Impl cad = new Carro_Impl();
        cad.pesquisarava(vencarpesquisa.getText(),vencartabela);
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aluprincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton venaddcliente;
    private javax.swing.JTextField vencarpesquisa;
    private javax.swing.JTable vencartabela;
    private javax.swing.JTextField venclipesquisa;
    public javax.swing.JTable venclitabela;
    private javax.swing.JComboBox<String> venhorainicio;
    private com.toedter.calendar.JDateChooser veninicio;
    private javax.swing.JTextField vennomcliente;
    private javax.swing.JFormattedTextField venplacarro;
    // End of variables declaration//GEN-END:variables
}
